FOLLOW = {
    "program": {"$"},
    "global": {"brain", "str", "int", "float", "char", "bool", "void"},
    "dtype": {"ID", "heart"},
    "dtype1": {"ID", "heart"},
    "gDec": {";"},
    "arOpt": {";"},
    "A2dArray": {";"},
    "A2dRow": {"}"},
    "element": {"}"},
    "literal": {";", "}", ","},
    "litOp": {")", ";", "}", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "eLit": {"}"},
    "gDecOp": {";"},
    "multiV": {";"},
    "fDec": {";"},
    "fArray": {";"},
    "f2dRow": {"}"},
    "multiFix": {";"},
    "func": {"brain"},
    "cloType": {"heart"},
    "param": {")"},
    "multiPar": {")"},
    "stmt": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "stmtOp": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "strTail": {";"},
    "index": {"]"},
    "strTail1": {";"},
    "strMulti": {";"},
    "strVal": {";", ","},
    "eleIndex": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^", "++", "--"},
    "A2Dindex": {")", ";", "=", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^", "++", "--"},
    "echOp": {")"},
    "echoMulti": {")"},
    "locDec": {";"},
    "locDecOp": {";"},
    "locMV": {";"},
    "exprDec": {")", ";", ","},
    "exprOr": {")", ";", ","},
    "exprOrTail": {")", ";", ","},
    "exprAnd": {")", ";", ",", "||"},
    "exprAndTail": {")", ";", ",", "||"},
    "exprRel": {")", ";", ",", "||", "&&"},
    "exprRelTail": {")", ";", ",", "||", "&&"},
    "exprAdd": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<="},
    "exprAddTail": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<="},
    "exprMul": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-"},
    "exprMulTail": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-"},
    "exprExp": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//"},
    "exprExpTail": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//"},
    "exprUnary": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "primary": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "unaOp": {")", ";", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "una1": {")", ";", "=", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "una": {")", ";", "ID", "=", ",", "||", "&&", "==", "!=", ">", "<", ">=", "<=", "+", "-", "*", "/", "%", "//", "^"},
    "locFDOp": {";"},
    "fixStrTail": {";"},
    "fixStrMulti": {";"},
    "fixLocDec": {";"},
    "idExpr": {";"},
    "arrIDTail": {";"},
    "assVal": {")", ";", ","},
    "comOp": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "spillOpt": {")"},
    "spillOpt1": {")", ","},
    "spillTail": {")"},
    "din": {";"},
    "dinTail": {";"},
    "dinTail1": {";"},
    "dup": {")"},
    "dupTail": {")"},
    "loopStmt": {"}"},
    "hopeTailLoop": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "despairOptLoop": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "coreCon": {")"},
    "coreAdd": {")"},
    "coreAddTail": {")"},
    "coreMul": {")", "+", "-"},
    "coreMulTail": {")", "+", "-"},
    "coreExp": {")", "+", "-", "*", "/", "%", "//"},
    "coreExpTail": {")", "+", "-", "*", "/", "%", "//"},
    "coreUnary": {")", "+", "-", "*", "/", "%", "//", "^"},
    "corePrimary": {")", "+", "-", "*", "/", "%", "//", "^"},
    "memVal": {")", "+", "-", "*", "/", "%", "//", "^", ":"},
    "coreLoopBody": {"}"},
    "closureCon": {";"},
    "hopeTail": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "despairOpt": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "stmtOpTail": {"}"},
    "coreBody": {"}"},
    "coreStmt": {"}"}
}