# follow_set

FOLLOW = {
    "program": {"$"},
    "global": {"brain", "str", "int", "float", "char", "bool", "void"},
    "dtype": {"ID", "heart"},
    "dtype1": {"ID", "heart"},
    "gDec": {";"},
    "arOpt": {";"},
    "element": {"}"},
    "literal": {";", "}", ","},
    "litOp": {")", ";", "}", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "eLit": {"}"},
    "gDecOp": {";"},
    "multiV": {";"},
    "fDec": {";"},
    "multiFix": {";"},
    "func": {"brain"},
    "cloType": {"heart"},
    "param": {")"},
    "multiPar": {")"},
    "stmt": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "stmtOp": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "strTail": {";"},
    "index": {"]"},
    "strTail1": {";"},
    "strArrTail": {";"},
    "strMulti": {";"},
    "strVal": {";", ","},
    "eleIndex": {")", ";", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "echOp": {")"},
    "echoMulti": {")"},
    "locDec": {";"},
    "locDecOp": {";"},
    "locMV": {";"},
    "exprDec": {")", ";", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "value2": {")", ";", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "exprTail": {")", ";", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "unaOp": {")", ";", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "una1": {")", ";", "=", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "una": {")", ";", "ID", "=", ",", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "operator": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "mathOp": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "locFDOp": {";"},
    "fixStrTail": {";"},
    "fixStrMulti": {";"},
    "fixLocDec": {";"},
    "idExpr": {";"},
    "arrIDTail": {";"},
    "assVal": {")", ";", ","},
    "comOp": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "readTail": {")"},
    "spillOpt": {")"},
    "spillOpt1": {")", ","},
    "spillTail": {")"},
    "din": {";"},
    "dinTail": {";"},
    "dinTail1": {";"},
    "dup": {")"},
    "dupTail": {")"},
    "loopStmt": {"}"},
    "hopeTailLoop": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "despairOptLoop": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "coreCon": {")"},
    "coreOp": {")", "+", "-", "*", "/", "%", "//", "^"},
    "memVal": {")", "+", "-", "*", "/", "%", "//", "^", ":"},
    "coreVal": {")"},
    "coreLoopBody": {"}"},
    "closureCon": {";"},
    "hopeTail": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "despairOpt": {"closure", "}", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
    "stmtOpTail": {"}"},
    "coreBody": {"}"},
    "coreStmt": {"}"},
}