FIRST = {
    "program": {"brain", "fixed", "str", "int", "float", "char", "bool", "void"},
    "global": {"fixed", "str", "int", "float", "char", "bool"},
    "dtype": {"str", "int", "float", "char", "bool"},
    "dtype1": {"int", "float", "char", "bool"},
    "gDec": {"[", "=", ","},
    "arOpt": {"[", "="},
    "A2dArray": {"="},
    "A2dRow": {","},
    "element": {"INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "literal": {"INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "litOp": {"INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "eLit": {","},
    "gDecOp": {"=", ","},
    "multiV": {","},
    "fDec": {"[", "="},
    "fArray": {"[", "="},
    "f2dRow": {","},
    "multiFix": {","},
    "func": {"str", "int", "float", "char", "bool", "void"},
    "cloType": {"str", "int", "float", "char", "bool", "void"},
    "param": {"str", "int", "float", "char", "bool"},
    "multiPar": {","},
    "stmt": {"ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--"},
    "stmtOp": {"ID", "fixed", "str", "int", "float", "char", "bool", "read", "spill", "desire", "while", "do", "echo", "++", "--"},
    "strTail": {"[", "=", ","},
    "index": {"ID", "INTLIT"},
    "strTail1": {"=", ","},
    "strMulti": {","},
    "strVal": {"ID", "STRLIT", "echo"},
    "eleIndex": {"["},
    "A2Dindex": {"["},
    "echOp": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "echoMulti": {","},
    "locDec": {"[", "=", ","},
    "locDecOp": {"=", ","},
    "locMV": {","},
    "exprDec": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprOr": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprOrTail": {"||"},
    "exprAnd": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprAndTail": {"&&"},
    "exprRel": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprRelTail": {"==", "!=", ">", "<", ">=", "<="},
    "exprAdd": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprAddTail": {"+", "-"},
    "exprMul": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprMulTail": {"*", "/", "%", "//"},
    "exprExp": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprExpTail": {"^"},
    "exprUnary": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "primary": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo"},
    "unaOp": {"[", "++", "--"},
    "una1": {"++", "--"},
    "una": {"++", "--"},
    "locFDOp": {"str", "int", "float", "char", "bool"},
    "fixStrTail": {"[", "="},
    "fixStrMulti": {","},
    "fixLocDec": {"[", "="},
    "idExpr": {"[", "=", "++", "--", "+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "arrIDTail": {"=", "++", "--"},
    "assVal": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "comOp": {"+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "spillOpt": {"ID", "STRLIT", "++", "--"},
    "spillOpt1": {"ID", "STRLIT", "++", "--"},
    "spillTail": {","},
    "din": {"ID", "int", "float", "char", "bool", "echo", "++", "--"},
    "dinTail": {"="},
    "dinTail1": {"[", "=", "||", "++", "--"},
    "dup": {"ID", "++", "--"},
    "dupTail": {"[", "||", "++", "--", "+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "loopStmt": {"closure", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "hopeTailLoop": {"despair"},
    "despairOptLoop": {"{", "hope"},
    "coreCon": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "coreAdd": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "coreAddTail": {"+", "-"},
    "coreMul": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "coreMulTail": {"*", "/", "%", "//"},
    "coreExp": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "coreExpTail": {"^"},
    "coreUnary": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "corePrimary": {"(", "ID", "INTLIT", "CHARLIT", "echo"},
    "memVal": {"INTLIT", "CHARLIT"},
    "coreLoopBody": {"memory", "default"},
    "closureCon": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "hopeTail": {"despair"},
    "despairOpt": {"{", "hope"},
    "stmtOpTail": {"closure"},
    "coreBody": {"memory", "default"},
    "coreStmt": {"closure", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
}