# first_set

FIRST = {
    "program": {"brain", "fixed", "str", "int", "float", "char", "bool", "void"},
    "global": {"fixed", "str", "int", "float", "char", "bool"},
    "dtype": {"str", "int", "float", "char", "bool"},
    "dtype1": {"int", "float", "char", "bool"},
    "gDec": {"[", "=", ","},
    "arOpt": {"="},
    "element": {"INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "literal": {"INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "litOp": {"INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray"},
    "eLit": {","},
    "gDecOp": {"=", ","},
    "multiV": {","},
    "fDec": {"[", "="},
    "multiFix": {","},
    "func": {"str", "int", "float", "char", "bool", "void"},
    "cloType": {"str", "int", "float", "char", "bool", "void"},
    "param": {"str", "int", "float", "char", "bool"},
    "multiPar": {","},
    "stmt": {"ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--"},
    "stmtOp": {"ID", "fixed", "str", "int", "float", "char", "bool", "read", "spill", "desire", "while", "do", "echo", "++", "--"},
    "strTail": {"[", "=", ","},
    "index": {"ID", "INTLIT"},
    "strTail1": {"=", ","},
    "strArrTail": {"="},
    "strMulti": {","},
    "strVal": {"ID", "STRLIT", "echo"},
    "eleIndex": {"["},
    "echOp": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "echoMulti": {","},
    "locDec": {"[", "=", ","},
    "locDecOp": {"=", ","},
    "locMV": {","},
    "exprDec": {"(", "ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "value2": {"ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "exprTail": {"==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "unaOp": {"[", "++", "--"},
    "una1": {"++", "--"},
    "una": {"++", "--"},
    "operator": {"==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "mathOp": {"+", "-", "*", "/", "%", "//", "^"},
    "locFDOp": {"str", "int", "float", "char", "bool"},
    "fixStrTail": {"[", "="},
    "fixStrMulti": {","},
    "fixLocDec": {"[", "="},
    "idExpr": {"(", "ID", "[", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--", "+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "arrIDTail": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "assVal": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "comOp": {"+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "readTail": {","},
    "spillOpt": {"ID", "STRLIT", "++", "--"},
    "spillOpt1": {"ID", "STRLIT", "++", "--"},
    "spillTail": {","},
    "din": {"ID", "int", "float", "char", "bool", "echo", "++", "--"},
    "dinTail": {"="},
    "dinTail1": {"[", "=", "++", "--", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^"},
    "dup": {"ID", "++", "--"},
    "dupTail": {"[", "++", "--", "==", "!=", ">", "<", ">=", "<=", "&&", "||", "+", "-", "*", "/", "%", "//", "^", "+=", "-=", "*=", "/=", "%=", "//=", "^="},
    "loopStmt": {"closure", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "down", "over"},
    "hopeTailLoop": {"despair"},
    "despairOptLoop": {"{", "hope"},
    "coreCon": {"(", "ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "coreOp": {"ID", "INTLIT", "CHARLIT", "echo", "++", "--"},
    "memVal": {"INTLIT", "CHARLIT"},
    "coreVal": {"+", "-", "*", "/", "%", "//", "^"},
    "coreLoopBody": {"memory", "default"},
    "closureCon": {"(", "ID", "INTLIT", "STRLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "!", "++", "--"},
    "hopeTail": {"despair"},
    "despairOpt": {"{", "hope"},
    "stmtOpTail": {"closure"},
    "coreBody": {"memory", "default"},
    "coreStmt": {"closure", "ID", "fixed", "str", "int", "float", "char", "bool", "hope", "core", "read", "spill", "desire", "while", "do", "echo", "++", "--", "over"},
}