from pyparsing import And

from FRST import FIRST as FST
from FF import FOLLOW as FF

class SyntaxAnalyzer:
    def __init__(self, tokens, terminal=None):
        # This is the constructor method for our class. It takes two inputs: the required list of tokens generated by our lexer, 
        # and an optional terminal object for logging. This method initializes the object's state, setting up our communication 
        # channels and preparing the data for the analysis that follows.
        lex_errors = [t for t in tokens if "error" in str(t[1]).lower() or str(t[1]).lower() in ["invalid", "unknown"]]
        # is there any token with type containing "error" or type being "invalid" or "unknown" (case-insensitive)
        # tawag sa part na yarn is list comprehension. 
        # it creates a new list (lex_errors) by iterating through each token (t)
        #  in the input list (tokens) and checking if the type of the token (t[1]) 
        # contains the substring "error" or is equal to "invalid" or "unknown" (ignoring case).
        #  If any of these conditions are true, the token is included in the lex_errors list. 
        # This allows us to easily identify and handle any lexical errors that may have
        #  occurred during tokenization before proceeding with syntax analysis.
        if lex_errors:
        # If the lex_errors list is not empty, it means that there were lexical errors found in the tokens.
        #dito  yung if lex_errors na toh... ang ginagawa nya is to check if you lex_errors ba na list
        # may laman or wala... if may laman sya then it is = to true and it will execute the code inside the if block. if wala naman sya laman it is = to false and it will skip the code inside the if block.
        # if walang laman then false we will skip yung block of code na toh. 
            val, t_type, line, col = lex_errors[0]
            # ang tawag sa part na toh is tuple unpacking 
            # It takes the very first error found and breaks it 
            # apart into individual variables so you can work with them easily.
            # Once we know there are errors, this line extracts the details of the very first one.
            #  We unpack the error's value, type, line number, and column position into individual 
            # variables so we can generate a specific, helpful error message for the user.
            # why only the lex_errors[0]? 
            # Usually, when a compiler or script fails, it's standard practice to report the first error encountered
            #  and stop. If you tried to report 100 errors at once, the user might get overwhelmed.
            #  By grabbing lex_errors[0], the code focuses on the "root" problem that broke the scan.
            err_msg = f"Lexical Error: Found '{val}' at line {line}, col {col}. Syntax Analysis aborted."
            # yung err_msg na toh is a formatted string that creates a clear and informative error message for the user.
            # yung f"..." is called an f-string in Python, which allows you to embed expressions inside string literals using curly braces {}.
            # The f before the quotation marks tells Python: "Look inside the curly braces { } and replace the variable names with their actual
            #  values." Without that f, the computer would literally print the words "{val}" instead of the actual error.
            if terminal: terminal.log(err_msg)
            # This line checks if a terminal object was provided (i.e., if terminal is not None). 
            # If it exists, it calls the log method of the terminal object to display the error message.
            #  This allows the error to be shown in the terminal interface, providing immediate feedback to the user about the 
            # lexical error that was encountered.
            #It takes that error message we just built and sends it to the user interface (the terminal) so the person running the
            #  code actually sees what went wrong.
            # if terminal:This is a safety check. his prevents the program from crashing if you happen to be running the code in a "headless" mode 
            # (like a background server) where there is no screen to print to.
            # terminal.log(...): This calls a specific function (likely part of your custom UI or a library) to display the message.
            # (err_msg): This passes the string we created in the previous step into that log function.
            #"Once the error message is prepared, we check if the terminal object is active. If it is, we use its log method to output
            #  the message to the user. This ensures the error is visible in the console or UI before the process shuts down."
            raise Exception(err_msg)
            # an exception is a signal that something went wrong that the program doesn't know how to handle. 
            # By writing raise Exception, you are intentionally "crashing" the program.
            # we raise an Exception using our error message. This is a critical step because it force-stops the program. 
            # It ensures that we don't proceed to the next phase—the Syntax Analysis—with invalid or corrupted data.
        self.tokens = tokens
        #self represents the instance of the object itself.
        # tokens (on the right): This is a temporary "local" variable. Once the current function or block finishes, 
        # this variable usually disappears from the computer's memory.
        # self.tokens (on the left): This is an attribute. Because it is attached to self, 
        # other parts of your program (like the Parser or the Code Generator) can come along later
        self.terminal = terminal
        #We assign the passed-in terminal object to self.terminal. This is a key setup step that establishes a communication channel 
        # for our class. It allows our lexical and syntax analyzers to output real-time feedback and error messages to the specific UI
        #  or console being used by the system.
        self.pos = 0
        # We initialize self.pos to zero. This serves as our internal cursor or pointer. It tracks our current location within 
        # the input data, ensuring that we start our analysis from the very first character and move forward sequentially.

    def get_token_info(self):
        # method definition
        ignore = ["space", "newline", "tab", "ocmt", "mcmt"]
        # non-functional part of the code 
        while self.pos < len(self.tokens):
        # len (self.tokens) gives us the total number of tokens in the list. self.pos is our current position in that list.
        # This while loop serves as our traversal mechanism. It allows us to iterate through the entire token stream. 
        # By comparing our current position to the total length of the token list, 
        # we ensure that we process every single piece of code without accidentally overshooting the end of the data.
        # len() is a built in function to calculate the length of an object
            t_type = self.tokens[self.pos][1]
            # Here, we access the current token using self.pos as the index. The [1] retrieves the type of the token, 
            # which is crucial for our syntax analysis.
            # This line performs a targeted data extraction. We use self.pos to locate the current token in our stream,
            #  and then we use the index [1] to isolate its type. This allows the program to decide whether the current
            #  token is something it needs to process or something it should ignore, like a comment or whitespace.
            # SO BASICALLY YUNG TINATAWAG NATN YUNG TOKEN IN A CURRENT INDEX AND THAT INDEX WE CALL THE TYPE OF THAT TOKEN 
            # SINCE TOKEN FORMAT IS (value, type, line, column) so [1] is the type of the token.
            # TOKEN SET UP IS LIKE THIS [("int", "dtype", 1, 1), ("x", "ID", 1, 5), ("=", "assign", 1, 7), ("10", "INTLIT", 1, 9), (";", "semicolon", 1, 11)]
            # THE FIRST INDEX self.pos is the current position in the token list, and [1] is the type of the token at that position.
            if t_type in ignore: self.pos += 1
            # if yung t_type value matches yung nasa loob ng ignore list then we will execute the self.pos += 1 
            # which means we will move to the next token and check again if that token is also in the ignore list.
            else: break
            # if yung t_type value wala sa ignore then 
            # the break keyword immediately terminates the current loop
        if self.pos >= len(self.tokens):
            # This condition checks if we've reached or exceeded the end of the token list. 
            # If self.pos is greater than or equal to the total number of tokens, it means there are no more tokens to process.
            # This is a boundary validation check. We are checking if our position pointer has met or exceeded the total number of tokens. 
            # If it has, it signals that we have reached the end of the input stream, and we should stop trying to retrieve more data 
            # to avoid a system crash
            last_line = self.tokens[-1][2] if self.tokens else 1
            # this is a conditional assignment (also called a ternary operator) used to determine the last line number of
            #  your source code without crashing if the file is empty.
            # self.tokens[-1]: In Python, [-1] is shorthand for "the very last item in the list."
            # [2]: This accesses the 3rd element of that last token. In your project, index 2 is typically the Line Number.
            # if self.tokens: This checks if the list is actually populated. In Python, an empty list is "False" and a list with items is "True."
            # else 1: If the list is empty (no tokens were found), it defaults the line number to 1.
            last_col = self.tokens[-1][3] if self.tokens else 1
            # Similarly, we use this line to capture the last_col, or the final column position of our input. By accessing the fourth
            #  element (index 3) of our very last token, we can pinpoint the exact character coordinate where our analysis concluded.
            #  This provides a precise 'End of File' marker for our reporting system.
            return ("$", "$", last_line, last_col)
            #we return what is known as a sentinel token. By using the dollar-sign symbols, we provide a clear 'End of File' signal.
            #  We include the last_line and last_col coordinates so that if the parser finds an error at the very end of the file, 
            # it can still report exactly where the program finished. This ensures a clean and predictable termination of the lexical analysis phase
        return self.tokens[self.pos]
        # This line is the primary output of the method. Once we have successfully skipped over ignored elements and confirmed 
        # we are still within the bounds of the list, we return the current token at self.pos. 
        # This hands off the specific token—including its type, value, and location—to the syntax analyzer for further processing. 

    def peek_token(self, offset=1):
    # THIS IS ANOTHER METHOD DEFINITION CALLED PEEK_TOKEN
    # THIS IS CREATED TO BE A LOOK A HEAD 
    # The peek_token method allows us to look ahead in the token stream without actually consuming any tokens. 
    # offset=1 ; By setting it to =1, it means that if you just call peek_token(), it will automatically look for the very next valid token.
        count = 0
        #count variable at zero to act as our valid token tracker
        ignore = ["space", "newline", "tab", "ocmt", "mcmt"]
        # same logic lang sa taas. non-functional stuff. List named ignore, which is used to say what tokens should be ignore in the parsing 
        temp_pos = self.pos
        # we just create a new variable to store the position of the token.
        # we create a temporary variable to allow us to move forward without affecting the actual index or position 
        #We initialize temp_pos as a copy of our current position. This creates a temporary pointer that allows us to safely explore future tokens. 
        # By incrementing this temporary variable instead of our main class pointer, we can perform lookahead logic
        #  without 'consuming' the tokens or disrupting the actual state of our lexical analysis.
        while temp_pos < len(self.tokens):
        # This while loop serves as our traversal engine. It allows us to move our temporary pointer forward through the token list. 
        # The condition temp_pos < len(self.tokens) is our primary safety check;
        #  it ensures that our 'peek' operation never attempts to access an index beyond the end of the list, 
        # which would otherwise cause the compiler to crash.
            t_type = self.tokens[temp_pos][1]
            # Similar to the get_token_info method, we access the type of the token at our temporary position. 
            # This is crucial for determining whether we should count this token towards our offset or skip it as an ignored element.
            if t_type not in ignore:
            # This line tells the computer to only pay attention to the "important" parts of the code and ignore the
            #  "filler" (like spaces and comments).
                if count == offset: return self.tokens[temp_pos]
            #count: This is how many "important" (non-space) tokens you have seen so far.
            #    offset: This is how many tokens ahead you wanted to look (usually 1).
            #    return self.tokens[temp_pos]: If the count matches, the function grabs that specific token and hands it over.
                count += 1
                # The count += 1 line is how we track our progress. It only triggers when we encounter a functional token. 
                # This allows us to accurately skip over any number of spaces or comments until we've counted exactly as many 'real' 
                # tokens as the offset requires.
            temp_pos += 1
            # This line ensures the progression of our search. By incrementing temp_pos at the end of every loop iteration,
            #  we move our temporary pointer to the next index in the list. This allows us to eventually inspect every single
            #  token until we either find what we are looking for or reach the end of the file.
        return ("$", "$", 0, 0)
        #this is our fallback return statement. If our search loop reaches the end of the token list without finding a match for our offset, 
        # the function returns a sentinel 'EOF' token. This prevents the compiler from crashing and signals to the parser that it has 
        # processed the entire input stream.
  
    # the peek_token method is a lookahead mechanism. It allows the compiler to inspect future tokens without consuming them. 
    # By using a temporary position pointer and a counter, it bypasses ignored tokens like whitespace and comments until it
    #  finds the meaningful token at the specified offset. This 'preview' capability is essential for predictive parsing,
    #  where the program needs to know what follows the current token to make the correct grammatical decision.

    def error(self, expected, local_follow=None):
        # expected: This is a list of things the compiler wanted to see (e.g., it expected a ; or a }).
        # local_follow: This is an optional extra piece of info (usually used for advanced error recovery),
        # but here it’s mostly just a placeholder.
        val, t_type, line, col = self.get_token_info()
        #This line performs context extraction. By calling get_token_info, we synchronize our error reporter with the current 
        # state of the lexer. We capture the token's value and type, along with its precise coordinates (line and column). 
        # This ensures that the error message we present to the user points to the exact location of the syntax violation.
        found = "$" if val == "$" else val
        # This line handles the token string normalization. It checks if the current value is our special 'End of File' marker.
        #  If it is, we keep the symbol $; otherwise, we use the actual text of the token. This ensures that our final error message
        #  is descriptive and clearly identifies the specific character or symbol that triggered the syntax error.
        combined = []
        # We initialize an empty list called combined to serve as a staging area. Our goal is to take the raw list of expected tokens—which
        #  might contain duplicates or internal grammar symbols—and refine it into a unique, filtered list that makes sense to a human 
        # programmer.
        for e in expected:
        # The for loop is our iterator. It allows us to process the expected list element-by-element.
        #  By isolating each token as e, we can apply our 'filtering rules' (like removing duplicates) before we build the 
        # final error string.
            if e not in combined and e != "λ":
            # This line acts as a double-filter. First, it performs deduplication by checking if the token is already in our list. 
            # Second, it filters out internal grammar symbols like 'Lambda,' which represents an empty string in formal logic but 
            # is unhelpful to a human programmer. This ensures our error message is both clean and meaningful.
                combined.append(e)
                #list method
                # In Python, .append() means "add this to the end of the list."
                #If your combined list currently looks like: [';']
                #And you run combined.append('ID')
                #The list now looks like: [';', 'ID']
                # Once a token has passed our validation checks, we use combined.append(e) to store it in our refined list.
                #  This builds our final collection of valid syntax options, ensuring that only unique, relevant, and human-readable
                #  tokens are included in the error report.
        expected_str = ", ".join([f"'{item}'" for item in combined]) 
        #.join is a str method 
        #This line is responsible for string formatting. We use a list comprehension to wrap each expected token in single quotes for clarity, 
        # and then we use the join method to concatenate them into a single, comma-separated string. 
        # This transforms our internal data into a format that is easy for the developer to read.
        if len(combined) > 1:
            #len is a built in function to calculate the length of an object
            #This is a conditional formatting check. We use the len() function to determine how many valid tokens were expected at the point of failure.
            #  If there's more than one possibility, we trigger a logic branch that wraps the suggestions in parentheses.
            #  This visually signals to the developer that any one of those multiple options would have been syntactically correct.
            expected_str = f"( {expected_str} )"
            #This line uses an f-string for string interpolation. If our previous check determined there was more than one expected token,
            #  we wrap the entire string in parentheses. This provides a clear visual container for the user, grouping the multiple syntax 
            # possibilities together so they are easily distinguishable from the rest of the error message.
        msg = f"Syntax Error : Line {line} Column {col} . EXPECTED {expected_str} . BUT FOUND '{found}'"
        #This line is the assembly phase. We use an f-string to perform string interpolation, combining all our processed data points—the coordinates, 
        # the expected set, and the actual token found—into a single, cohesive diagnostic message. 
        # This msg string is what will ultimately be printed to the console to guide the developer in fixing their code.
        if self.terminal: self.terminal.log(msg)
        # Finally, we have the output phase. We check if a terminal instance is available, and if so, we call its log method. 
        # This decouples the error generation logic from the display logic, allowing us to pipe our finalized msg to a console, 
        # a file, or a UI component where the user can actually read it.
        raise Exception(msg)
        # Finally, we use the raise keyword to throw a formal Exception. This is critical because it halts the compilation process immediately.
        #  By passing our msg into the Exception, we ensure that the execution doesn't continue with invalid data, 
        # which would only lead to a cascade of more confusing errors. It forces the developer to stop and fix the syntax 
        # before the compiler proceeds any further.

    # This is our Error Reporting Engine. When the parser encounters something it doesn't understand, 
    # this method gathers the location (line and column) and the 'found' token. It then filters the list of 
    # 'expected' tokens to remove duplicates and empty symbols, creating a human-readable message. Finally, 
    # it logs the error and halts execution to prevent the compiler from processing invalid code.

    def match(self, expected, follow=None):
        # expected: This is what we want to see at this point in the grammar (e.g., a specific symbol or token type).
        # follow: This is an optional set of tokens that could validly come after the expected token. It's used for error reporting to provide more context.
        val, t_type, line, col = self.get_token_info()
        # This line retrieves the current token's value, type, and location. This information is crucial for both validating the token against our expectations and for generating informative error messages if the match fails.
        # By calling get_token_info, we ensure that we are working with the most up-to-date token data, which allows us to make accurate decisions in our parsing logic and provide precise feedback to the user in case of syntax errors.
        is_id_match = (expected == "ID" and t_type.startswith("ID"))
        # This line handles a special case for identifiers. In many programming languages, identifiers can have various forms (e.g., ID, ID1, ID2).
        # By checking if the expected token is "ID" and the actual token type starts with "ID," we allow for a flexible match that accommodates different identifier formats while still enforcing the requirement that it must be some form of identifier.
        # This logic is essential for correctly parsing variable names, function names, and other identifiers in the source code, ensuring that the syntax analyzer can recognize them even if they have different suffixes or variations.
        # This line is a conditional check that determines whether the current token matches our expectations. We compare the token's value and type against the expected criteria, and we also account for the special case of identifiers. If any of these conditions are met, we consider it a successful match.
        # If the match is successful, we advance our position pointer to consume the token and return its value for further processing in the parsing logic. If the match fails, we trigger the error reporting mechanism to inform the user of the syntax violation.
        if val == expected or t_type == expected or is_id_match:
            #This line serves as our multi-criteria validation gate. We use a logical OR to provide three different ways for a token to be considered a match.
            #  This gives the parser the flexibility to match against literal strings, token categories, or specialized identifier groups. 
            # If any of these conditions are met, the parser confirms that the input sequence aligns with our defined grammar.
            self.pos += 1
            # Once a match is confirmed, we perform pointer incrementation. By increasing self.pos by one, we effectively 'consume' the current token and advance the parser's state to the next position in the token stream. 
            # This ensures that the compilation process moves forward linearly and prevents the parser from re-evaluating the same input indefinitely.
            return val 
            # we return the captured value to the calling function. While the primary job of match is validation, the parser often needs the actual string content of the token—such as a variable name or a numeric literal—to construct the Abstract Syntax Tree or update the symbol table. 
            # This return statement ensures that the semantic data is preserved even as we advance through the syntax.
        else:
            if isinstance(expected, list):
                #isinstance(expected, list): This is a built-in Python function that asks a question: 
                # "Is the expected variable a List (like ['+', '-']) or just a single item (like ';')?
                self.error(expected, follow)
                # If expected is a list, we pass it directly to the error method. This allows the error reporting system to generate a message that includes all the valid options that were expected at this point in the grammar, providing more comprehensive feedback to the user.
                # By passing the entire list of expected tokens, we can inform the developer that multiple different inputs would have been acceptable, which can be especially helpful in cases where the grammar allows for several alternatives.
                # If expected is not a list, we still want to report it as an error, but we can simply wrap it in a list to maintain consistency in our error reporting format. This way, the error method can always expect a list of expected tokens, regardless of whether there was originally one or many.
            else:
                # If expected is not already a list, we create a new list containing the single expected token. This ensures that our error reporting system can handle both singular and multiple expected tokens without needing separate logic for each case.
                # By standardizing the expected input to always be a list, we simplify the error reporting process and ensure that our messages are consistently formatted, making it easier for developers to understand what went wrong and how to fix it.
                # This line is a type check and normalization step. We use isinstance to determine if expected is already a list. If it is not, we create a new list containing the single expected token. This ensures that our error reporting system can handle both singular and multiple expected tokens in a consistent manner, simplifying the logic for generating error messages.
                # By ensuring that expected is always a list, we can use the same error reporting logic regardless of whether we were originally expecting one token or several, which enhances the robustness and maintainability of our syntax analyzer.
                # This line is a type check and normalization step. We use isinstance to determine if expected is already a list. If it is not, we create a new list containing the single expected token. This ensures that our error reporting system can handle both singular and multiple expected tokens in a consistent manner, simplifying the logic for generating error messages.
                self.error([expected], follow)

    # The match method is our token validation checkpoint. It checks if the current token matches what we expect at that point in the grammar.

    def parse_program(self):
        _, _, line, _ = self.get_token_info()
        node = {"type": "program", "global": None, "function": None, "stmt": None, "line": line}
        val, t_type, line, col = self.get_token_info()
        if t_type in FST["global"] or val == "fixed" or t_type.startswith("ID"):
            node["global"] = self.parse_global({"heart", "void", "brain"} | FST["dtype"])
        val, t_type, line, col = self.get_token_info()
        if t_type in FST["dtype"] or val == "void":
            node["function"] = self.parse_func({"brain"})
        self.match("brain")
        self.match("(")
        self.match(")")
        self.match("{")
        node["stmt"] = self.parse_stmt({"closure", "}"})
        self.match("closure")
        self.match("0")
        self.match(";")
        self.match("}")
        return node

    def parse_global(self, local_follow):
        node = {"type": "global", "declarations": []}
        val, t_type, line, col = self.get_token_info()
        if t_type in ["brain", "void"]:
            return node
        if t_type in FST["dtype"]:
            decl_line = line
            self.pos += 1
            nv, nt, nl, nc = self.get_token_info()
            if nt != "ID" and not nt.startswith("ID") and nv != "heart":
                self.error(["ID", "heart"])
            if nv == "heart":
                self.pos -= 1
                return node
            decl = {"type": "global", "dtype": val, "line": decl_line}
            decl["name"] = self.match("ID", FST["gDec"] | {";"})
            decl["dec"] = self.parse_gDec({";"})
            node["declarations"].append(decl)
            self.match(";", FST["global"] | local_follow)
            rest = self.parse_global(local_follow)
            node["declarations"].extend(rest["declarations"])
        elif val == "fixed":
            decl_line = line
            self.pos += 1
            decl = {"type": "global", "fixed": True, "line": decl_line}
            decl["dtype"] = self.parse_dtype(FST["dtype"])
            decl["name"] = self.match("ID", FST["fDec"] | {";"})
            decl["dec"] = self.parse_fDec({";"})
            node["declarations"].append(decl)
            self.match(";", FST["global"] | local_follow)
            rest = self.parse_global(local_follow)
            node["declarations"].extend(rest["declarations"])
        elif t_type in FST["func"] and val == "brain":
            return node
        else:
            self.error(list(FF["global"]), local_follow)
        return node

    def parse_dtype(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type == "str":
            self.pos += 1
            return val
        elif t_type in FST["dtype1"]:
            return self.parse_dtype1(local_follow)
        else:
            self.error(list(FST["dtype"]), local_follow)

    def parse_dtype1(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type in FST["dtype1"]:
            self.pos += 1
            return val
        else:
            self.error(list(FST["dtype1"]), local_follow)

    def parse_gDec(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "gDec", "line": line}
        if val == "[":
            self.pos += 1
            node["size"] = self.match("INTLIT", ["]"])
            self.match("]", FST["arOpt"] | {";"})
            node["arOpt"] = self.parse_arOpt(local_follow)
        elif val in FST["gDecOp"] or val == ";":
            node["gDecOp"] = self.parse_gDecOp(";")
        else:
            self.error(list(FST["gDec"]) + [";"], local_follow)
        return node

    def parse_arOpt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "arOpt", "line": line}
        if val == "[":
            self.pos += 1
            node["size2"] = self.match("INTLIT", ["]"])
            self.match("]")
            node["2dArray"] = self.parse_2dArray(local_follow)
        elif val == "=":
            self.pos += 1
            self.match("{")
            node["elements"] = self.parse_element({"}"})
            self.match("}")
        elif val in FF["arOpt"]:
            return node
        else:
            self.error(list(FST["arOpt"]) + list(FF["arOpt"]), local_follow)
        return node
    
# hanggang dito nalang same logic will be applied naman sa mga susunod na methods 

    def parse_2dArray(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "2dArray", "rows": [], "line": line}
        if val == "=":
            self.pos += 1
            self.match("{")
            self.match("{")
            row1 = self.parse_element({"}"})
            self.match("}")
            rows = [row1]
            self.parse_2dRow(rows, local_follow)
            self.match("}")
            node["rows"] = rows
        return node

    def parse_2dRow(self, rows, local_follow):
        val, t_type, line, col = self.get_token_info()
        if val == ",":
            self.pos += 1
            self.match("{")
            row = self.parse_element({"}"})
            self.match("}")
            rows.append(row)
            self.parse_2dRow(rows, local_follow)
        elif val == "}":
            pass
        else:
            self.error([",", "}"], local_follow)

    def parse_element(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "element", "literals": [], "line": line}
        if t_type in FST["literal"]:
            node["literals"].append(self.parse_literal({",", "}"}))
            node["literals"].extend(self.parse_eLit({"}"}) or [])
        elif val in FF["element"]:
            return node
        else:
            self.error(list(FST["element"]) + ["}"], local_follow)
        return node

    def parse_literal(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type == "STRLIT":
            self.pos += 1
            return val
        elif t_type in FST["litOp"]:
            return self.parse_litOp(local_follow)
        else:
            self.error(list(FST["literal"]), local_follow)

    def parse_litOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type in FST["litOp"]:
            self.pos += 1
            return val
        else:
            self.error(list(FST["litOp"]), local_follow)

    def parse_eLit(self, local_follow):
        items = []
        val, t_type, line, col = self.get_token_info()
        if val == ",":
            self.pos += 1
            items.append(self.parse_literal(local_follow))
            items.extend(self.parse_eLit(local_follow) or [])
        elif val in FF["eLit"]:
            return items
        else:
            self.error(list(FST["eLit"]) + ["}"], local_follow)
        return items

    def parse_gDecOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "gDecOp", "line": line}
        if val == "=":
            self.pos += 1
            node["value"] = self.parse_literal(local_follow)
            node["multiV"] = self.parse_multiV(local_follow)
        elif val in FST["multiV"]:
            node["multiV"] = self.parse_multiV(local_follow)
        elif val in FF["gDecOp"]:
            return node
        else:
            self.error(list(FST["gDecOp"]) + list(FST["multiV"]) + list(FF["gDecOp"]), local_follow)
        return node

    def parse_multiV(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "multiV", "vars": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"name": self.match("ID"), "line": line}
            entry["gDecOp"] = self.parse_gDecOp(local_follow)
            node["vars"].append(entry)
        elif val in FF["multiV"]:
            return node
        else:
            self.error(list(FF["multiV"]) + list(FST["multiV"]), local_follow)
        return node

    def parse_fDec(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "fDec", "line": line}
        if val == "[":
            self.pos += 1
            node["size"] = self.match("INTLIT", ["]"])
            self.match("]")
            node["fArray"] = self.parse_fArray(local_follow)
        elif val == "=":
            self.pos += 1
            node["value"] = self.parse_literal(local_follow)
            node["multiFix"] = self.parse_multiFix(local_follow)
        else:
            self.error(list(FST["fDec"]), local_follow)
        return node

    def parse_fArray(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "fArray", "line": line}
        if val == "[":
            self.pos += 1
            node["size2"] = self.match("INTLIT", ["]"])
            self.match("]")
            self.match("=")
            self.match("{")
            rows = []
            self.match("{")
            row_lits = [self.parse_literal({"}", ","})]
            row_lits.extend(self.parse_eLit({"}", ","}) or [])
            self.match("}")
            rows.append({"literals": row_lits})
            self.parse_f2dRow(rows, local_follow)
            self.match("}")
            node["2dArray"] = {"rows": rows}
        elif val == "=":
            self.pos += 1
            self.match("{")
            node["literals"] = [self.parse_literal({"}"})]
            node["literals"].extend(self.parse_eLit({"}"}) or [])
            self.match("}")
        else:
            self.error(["[", "="], local_follow)
        return node

    def parse_f2dRow(self, rows, local_follow):
        val, t_type, line, col = self.get_token_info()
        if val == ",":
            self.pos += 1
            self.match("{")
            row_lits = [self.parse_literal({"}", ","})]
            row_lits.extend(self.parse_eLit({"}", ","}) or [])
            self.match("}")
            rows.append({"literals": row_lits})
            self.parse_f2dRow(rows, local_follow)
        elif val == "}":
            pass
        else:
            self.error([",", "}"], local_follow)
   
    def parse_multiFix(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "multiFix", "vars": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"name": self.match("ID"), "line": line}
            self.match("=")
            entry["value"] = self.parse_literal(local_follow)
            node["vars"].append(entry)
            rest = self.parse_multiFix(local_follow)
            node["vars"].extend(rest["vars"])
        elif val in FF["multiFix"]:
            return node
        else:
            self.error(list(FST["multiFix"]) + list(FF["multiFix"]), local_follow)
        return node

    def parse_func(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "func", "functions": [], "line": line}
        if val == "brain":
            return node
        if val in FST["func"]:
            func = {"line": line}
            func["return_type"] = self.parse_cloType({"heart"})
            self.match("heart", ["ID"])
            func["name"] = self.match("ID", ["("])
            self.match("(", FST["dtype"] | {")"})
            func["param"] = self.parse_param({")"})
            self.match(")", ["{"])
            self.match("{")
            func["stmt"] = self.parse_stmt({"closure"})
            self.match("closure")
            func["closureCon"] = self.parse_closureCon({";"})
            self.match(";", ["}"])
            self.match("}")
            node["functions"].append(func)
            rest = self.parse_func(local_follow)
            node["functions"].extend(rest["functions"])
        else:
            self.error(list(FST["func"]) + list(FF["func"]), local_follow)
        return node

    def parse_cloType(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if val == "void":
            self.pos += 1
            return val
        elif t_type in FST["dtype"]:
            return self.parse_dtype(local_follow)
        else:
            self.error(list(FST["cloType"]), local_follow)

    def parse_param(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "param", "params": [], "line": line}
        if t_type in FST["dtype"]:
            entry = {"line": line}
            entry["dtype"] = self.parse_dtype({"ID"})
            entry["name"] = self.match("ID", FST["multiPar"] | FF["multiPar"])
            node["params"].append(entry)
            rest = self.parse_multiPar(local_follow)
            node["params"].extend(rest["params"])
        elif val in FF["param"]:
            return node
        else:
            self.error(list(FST["param"]) + list(FF["param"]), local_follow)
        return node

    def parse_multiPar(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "multiPar", "params": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"line": line}
            entry["dtype"] = self.parse_dtype({"ID"})
            entry["name"] = self.match("ID", FST["multiPar"] | FF["multiPar"])
            node["params"].append(entry)
            rest = self.parse_multiPar(local_follow)
            node["params"].extend(rest["params"])
        elif val in FF["multiPar"]:
            return node
        else:
            self.error(list(FST["multiPar"]) + list(FF["multiPar"]), local_follow)
        return node

    def parse_stmt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "stmt", "stmts": [], "line": line}
        if val == "hope":
            self.pos += 1
            stmt = {"type": "hope", "line": line}
            self.match("(")
            stmt["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match("{")
            stmt["stmt"] = self.parse_stmt({"closure", "}"})
            stmt["stmtOpTail"] = self.parse_stmtOpTail({ "}"})
            self.match("}")
            stmt["hopeTail"] = self.parse_hopeTail(FST["stmt"] | local_follow)
            node["stmts"].append(stmt)
            rest = self.parse_stmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val == "core":
            self.pos += 1
            stmt = {"type": "core", "line": line}
            self.match("(")
            stmt["condition"] = self.parse_coreCon({")"})
            self.match(")")
            self.match("{")
            stmt["body"] = self.parse_coreBody({"}"})
            self.match("}")
            node["stmts"].append(stmt)
            rest = self.parse_stmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif t_type in FST["stmtOp"] or val in FST["stmtOp"] or t_type.startswith("ID"):
            node["stmts"].append(self.parse_stmtOp(FST["stmt"] | local_follow))
            rest = self.parse_stmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val in ["closure", "}"] or val in local_follow:
            return node
        else:
            self.error(list(FST["stmt"]) + list(local_follow), local_follow)
        return node

    def parse_stmtOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "stmtOp", "line": line}
        if t_type == "str":
            self.pos += 1
            node["kind"] = "str"
            node["name"] = self.match("ID")
            node["strTail"] = self.parse_strTail({";"})
            self.match(";")
        elif t_type in FST["dtype1"]:
            node["kind"] = "dtype1"
            node["dtype"] = self.parse_dtype1(local_follow)
            node["name"] = self.match("ID")
            node["locDec"] = self.parse_locDec({";"})
            self.match(";")
        elif val == "fixed":
            self.pos += 1
            node["kind"] = "fixed"
            node["locFDOp"] = self.parse_locFDOp({";"})
            self.match(";")
        elif t_type == "ID" or t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            node["idExpr"] = self.parse_idExpr({";"})
            self.match(";")
        elif val == "read":
            self.pos += 1
            node["kind"] = "read"
            self.match("(")
            node["id"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex({")"})
            self.match(")")
            self.match(";")
        elif val == "spill":
            self.pos += 1
            node["kind"] = "spill"
            self.match("(")
            node["spillOpt"] = self.parse_spillOpt({")"})
            self.match(")")
            self.match(";")
        elif val == "desire":
            self.pos += 1
            node["kind"] = "desire"
            self.match("(")
            node["din"] = self.parse_din({";"})
            self.match(";")
            node["condition"] = self.parse_exprDec({";"})
            self.match(";")
            node["dup"] = self.parse_dup({")"})
            self.match(")")
            self.match("{")
            node["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
        elif val == "while":
            self.pos += 1
            node["kind"] = "while"
            self.match("(")
            node["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match("{")
            node["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
        elif val == "do":
            self.pos += 1
            node["kind"] = "do"
            self.match("{")
            node["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
            self.match("while")
            self.match("(")
            node["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match(";")
        elif val == "echo":
            self.pos += 1
            node["kind"] = "echo"
            node["name"] = self.match("ID")
            self.match("(")
            node["echOp"] = self.parse_echOp({")"})
            self.match(")")
            self.match(";")
        elif t_type in FST["una"]:
            node["kind"] = "una"
            node["op"] = self.parse_una({"ID"})
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex({";"})
            self.match(";")
        else:
            self.error(list(FST["stmtOp"]), local_follow)
        return node

    def parse_strTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "strTail", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["strArrTail"] = self.parse_strArrTail(local_follow) # in cfg its locArr  
        elif val in FST["strTail1"] or val in FF["strTail1"]:
            node["strTail1"] = self.parse_strTail1(local_follow)
        else:
            self.error(list(FST["strTail"]) + list(FF["strTail"]), local_follow)
        return node

    def parse_index(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type == "INTLIT":
            self.pos += 1
            return val
        elif t_type == "ID" or t_type.startswith("ID"):
            self.pos += 1
            return val
        else:
            self.error(["INTLIT", "ID"], local_follow)

    def parse_strTail1(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "strTail1", "line": line}
        if val == "=":
            self.pos += 1
            node["value"] = self.parse_strVal(FST["strMulti"] | local_follow)
            node["strMulti"] = self.parse_strMulti(local_follow)
        elif val in FST["strMulti"] or val in FF["strMulti"]:
            node["strMulti"] = self.parse_strMulti(local_follow)
        else:
            self.error(list(FST["strTail1"]) + list(FF["strTail1"]), local_follow)
        return node
# idonthave strArrtail in the system. what i have is locArr. they are kinda same 
# i will keep the strArrtail in the system for now  
    def parse_strArrTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "strArrTail", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["2dArray"] = self.parse_2dArray(local_follow)
        elif val == "=":
            self.pos += 1
            self.match("{")
            node["elements"] = self.parse_element({"}"})
            self.match("}")
        elif val in FF["strArrTail"]:
            return node
        else:
            self.error(list(FST["strArrTail"]) + list(FF["strArrTail"]), local_follow)
        return node
    
    def parse_strMulti(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "strMulti", "vars": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"line": line}
            entry["name"] = self.match("ID")
            entry["strTail1"] = self.parse_strTail1(local_follow)
            node["vars"].append(entry)
        elif val in FF["strMulti"]:
            return node
        else:
            self.error(list(FST["strMulti"]) + list(FF["strMulti"]), local_follow)
        return node

    def parse_strVal(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "strVal", "line": line}
        if val == "echo":
            self.pos += 1
            node["kind"] = "echo"
            node["name"] = self.match("ID")
            self.match("(")
            node["echOp"] = self.parse_echOp({")"})
            self.match(")")
        elif t_type == "STRLIT":
            self.pos += 1
            node["kind"] = "STRLIT"
            node["value"] = val
        elif t_type == "ID" or t_type.startswith("ID"):
            self.pos += 1
            node["kind"] = "ID"
            node["name"] = val
            node["eleIndex"] = self.parse_eleIndex({"[", ",", ";"})
        else:
            self.error(list(FST["strVal"]), local_follow)
        return node

    def parse_eleIndex(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "eleIndex", "index": None, "index2": None, "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["index2"] = self.parse_2dIndex(local_follow)
        elif val in FF["eleIndex"] or t_type in FF["eleIndex"]:
            return node
        else:
            self.error(list(FST["eleIndex"]) + list(local_follow), local_follow)
        return node

    def parse_2dIndex(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "2dIndex", "index": None, "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
        else:
            return node
        return node

    def parse_echOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "echOp", "args": [], "line": line}
        if t_type in FST["assVal"] or val in FST["assVal"] or t_type.startswith("ID"):
            node["args"].append(self.parse_assVal(FST["echoMulti"] | local_follow))
            node["args"].extend(self.parse_echoMulti(local_follow))
        elif val in FF["echOp"]:
            return node
        else:
            self.error(list(FST["echOp"]) + list(FF["echOp"]), local_follow)
        return node

    def parse_echoMulti(self, local_follow):
        items = []
        val, t_type, line, col = self.get_token_info()
        if val == ",":
            self.pos += 1
            items.append(self.parse_assVal(FST["echoMulti"] | local_follow))
            items.extend(self.parse_echoMulti(local_follow))
        elif val in FF["echoMulti"]:
            return items
        else:
            self.error(list(FST["echoMulti"]) + list(FF["echoMulti"]), local_follow)
        return items

    def parse_locDec(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "locDec", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["arOpt"] = self.parse_arOpt(local_follow) 
            # in cfg its locArrOpt but i will keep it arOpt in the system
            # since it is doing the same thing as arOpt in global declaration
        elif val in FST["locDecOp"] or val in FF["locDecOp"]:
            node["locDecOp"] = self.parse_locDecOp(local_follow)
        else:
            self.error(list(FST["locDec"]) + list(FF["locDecOp"]), local_follow)
        return node

    def parse_locDecOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "locDecOp", "line": line}
        if val == "=":
            self.pos += 1
            node["value"] = self.parse_exprDec({","} | local_follow)
            node["locMV"] = self.parse_locMV(local_follow)
        elif val in FST["locMV"] or val in FF["locMV"]:
            node["locMV"] = self.parse_locMV(local_follow)
        else:
            self.error(list(FST["locDecOp"]) + list(FF["locDecOp"]), local_follow)
        return node

    def parse_locMV(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "locMV", "vars": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"line": line}
            entry["name"] = self.match("ID")
            entry["locDecOp"] = self.parse_locDecOp(local_follow)
            node["vars"].append(entry)
        elif val in FF["locMV"]:
            return node
        else:
            self.error(list(FST["locMV"]) + list(FF["locMV"]), local_follow)
        return node

    def parse_exprDec(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprDec", "line": line}
        node["exprOr"] = self.parse_expr_or(local_follow)
        return node

    def parse_expr_or(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprOr", "line": line}
        node["left"] = self.parse_expr_and({"||"} | local_follow)
        node["tail"] = self.parse_expr_or_tail(local_follow)
        return node

    def parse_expr_or_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprOrTail", "op": None, "right": None, "line": line}
        if val == "||":
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_and({"||"} | local_follow)
            node["tail"] = self.parse_expr_or_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_and(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprAnd", "line": line}
        node["left"] = self.parse_expr_rel({"&&"} | local_follow)
        node["tail"] = self.parse_expr_and_tail(local_follow)
        return node

    def parse_expr_and_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprAndTail", "op": None, "right": None, "line": line}
        if val == "&&":
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_rel({"&&"} | local_follow)
            node["tail"] = self.parse_expr_and_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_rel(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprRel", "line": line}
        rel_ops = {"==", "!=", ">", "<", ">=", "<="}
        node["left"] = self.parse_expr_add(rel_ops | local_follow)
        node["tail"] = self.parse_expr_rel_tail(local_follow)
        return node

    def parse_expr_rel_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprRelTail", "op": None, "right": None, "line": line}
        rel_ops = {"==", "!=", ">", "<", ">=", "<="}
        if val in rel_ops:
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_add(rel_ops | local_follow)
            node["tail"] = self.parse_expr_rel_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_add(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprAdd", "line": line}
        node["left"] = self.parse_expr_mul({"+", "-"} | local_follow)
        node["tail"] = self.parse_expr_add_tail(local_follow)
        return node

    def parse_expr_add_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprAddTail", "op": None, "right": None, "line": line}
        if val in {"+", "-"}:
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_mul({"+", "-"} | local_follow)
            node["tail"] = self.parse_expr_add_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_mul(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprMul", "line": line}
        node["left"] = self.parse_expr_exp({"*", "/", "%", "//"} | local_follow)
        node["tail"] = self.parse_expr_mul_tail(local_follow)
        return node

    def parse_expr_mul_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprMulTail", "op": None, "right": None, "line": line}
        if val in {"*", "/", "%", "//"}:
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_exp({"*", "/", "%", "//"} | local_follow)
            node["tail"] = self.parse_expr_mul_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_exp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprExp", "line": line}
        node["left"] = self.parse_expr_unary({"^"} | local_follow)
        node["tail"] = self.parse_expr_exp_tail(local_follow)
        return node

    def parse_expr_exp_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprExpTail", "op": None, "right": None, "line": line}
        if val == "^":
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_expr_unary({"^"} | local_follow)
            node["tail"] = self.parse_expr_exp_tail(local_follow)
        else:
            return node
        return node

    def parse_expr_unary(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "exprUnary", "line": line}
        if val == "!":
            self.pos += 1
            node["kind"] = "!"
            node["operand"] = self.parse_expr_unary(local_follow)
        elif val in {"++", "--"}:
            node["kind"] = val
            self.pos += 1
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex(local_follow)
        else:
            node["kind"] = "primary"
            node["primary"] = self.parse_primary(local_follow)
        return node

    def parse_primary(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "primary", "line": line}
        if val == "echo":
            self.pos += 1
            node["kind"] = "echo"
            node["name"] = self.match("ID")
            self.match("(")
            node["echOp"] = self.parse_echOp({")"})
            self.match(")")
        elif val == "(":
            self.pos += 1
            node["kind"] = "grouped"
            node["inner"] = self.parse_exprDec({")"})
            self.match(")")
        elif t_type in {"INTLIT", "FLOATLIT", "CHARLIT"} or val in {"trust", "betray"}:
            node["kind"] = t_type if t_type in {"INTLIT", "FLOATLIT", "CHARLIT"} else val
            node["value"] = val
            self.pos += 1
        elif t_type == "ID" or t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            node["postfix"] = self.parse_postfix(local_follow)
        else:
            self.error(["ID", "INTLIT", "FLOATLIT", "CHARLIT", "trust", "betray", "echo", "("], local_follow)
        return node
# NOT IN THE CFG 
    def parse_postfix(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "postfix", "index": None, "index2": None, "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["index2"] = self.parse_2dIndex(local_follow)
            node["unaPost"] = self.parse_una_post(local_follow)
        else:
            node["unaPost"] = self.parse_una_post(local_follow)
        return node

    def parse_una_post(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "unaPost", "op": None, "line": line}
        if val in {"++", "--"}:
            node["op"] = val
            self.pos += 1
        else:
            return node
        return node

    def parse_una(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if val in FST["una"]:
            self.pos += 1
            return val
        else:
            self.error(list(FST["una"]), local_follow)

    def parse_unaOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "unaOp", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["una1"] = self.parse_una1(local_follow)
        elif val in {"++", "--"}:
            node["op"] = val
            self.pos += 1
        else:
            return node
        return node

    def parse_una1(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "una1", "op": None, "line": line}
        if val in {"++", "--"}:
            node["op"] = val
            self.pos += 1
        elif val in local_follow:
            return node
        else:
            expected = ["++", "--"] + list(local_follow)
            self.error(sorted(list(set(expected))), local_follow)
        return node

    def parse_locFDOp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "locFDOp", "line": line}
        if t_type == "str":
            self.pos += 1
            node["kind"] = "str"
            node["name"] = self.match("ID")
            node["fixStrTail"] = self.parse_fixStrTail(local_follow)
        elif t_type in FST["dtype1"]:
            node["kind"] = "dtype1"
            node["dtype"] = self.parse_dtype1(local_follow)
            node["name"] = self.match("ID")
            node["fixLocDec"] = self.parse_fixLocDec(local_follow)
        else:
            self.error(list(FST["locFDOp"]), local_follow)
        return node

    def parse_fixStrTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "fixStrTail", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["fArray"] = self.parse_fArray(local_follow)
        elif val == "=":
            self.pos += 1
            node["value"] = self.match("STRLIT")
            node["fixStrMulti"] = self.parse_fixStrMulti(local_follow)
        else:
            self.error(list(FST["fixStrTail"]), local_follow)
        return node

    def parse_fixStrMulti(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "fixStrMulti", "vars": [], "line": line}
        if val == ",":
            self.pos += 1
            entry = {"line": line}
            entry["name"] = self.match("ID")
            self.match("=")
            entry["value"] = self.match("STRLIT")
            node["vars"].append(entry)
            rest = self.parse_fixStrMulti(local_follow)
            node["vars"].extend(rest["vars"])
        elif val in FF["fixStrMulti"]:
            return node
        else:
            self.error(list(FST["fixStrMulti"]) + list(FF["fixStrMulti"]), local_follow)
        return node

    def parse_fixLocDec(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "fixLocDec", "line": line}
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["fArray"] = self.parse_fArray(local_follow)
        elif val == "=":
            self.pos += 1
            node["value"] = self.parse_literal(FST["multiFix"] | local_follow)
            node["multiFix"] = self.parse_multiFix(local_follow)
        else:
            self.error(list(FST["fixLocDec"]) + list(FF["fixLocDec"]), local_follow)
        return node
    
# no comOp def because the system put the comOp terminal in the  list
# comOp = ["+=", "-=", "*=", "/=", "%=", "//=", "^="] 
# that's why nag work pa din yung system
    def parse_idExpr(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "idExpr", "line": line}
        comOp = ["+=", "-=", "*=", "/=", "%=", "//=", "^="]
        if val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            node["index2"] = self.parse_2dIndex({val for val in comOp} | {"++", "--", "="} | local_follow)
            node["arrIDTail"] = self.parse_arrIDTail(local_follow)
        elif val in comOp:
            node["op"] = val
            self.pos += 1
            node["exprDec"] = self.parse_exprDec(local_follow)
        elif val in ["++", "--"] or val == "=" or val in local_follow:
            node["arrIDTail"] = self.parse_arrIDTail(local_follow)
        else:
            expected = ["[", "++", "--", "="] + comOp
            self.error(expected, local_follow)
        return node

    def parse_arrIDTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "arrIDTail", "line": line}
        comOp = ["+=", "-=", "*=", "/=", "%=", "//=", "^="]
        if val in ["++", "--"]:
            node["op"] = val
            self.pos += 1
        elif val == "=":
            self.pos += 1
            node["assVal"] = self.parse_assVal(local_follow)
        elif val in comOp:
            node["op"] = val
            self.pos += 1
            node["exprDec"] = self.parse_exprDec(local_follow)
        elif val in local_follow:
            return node
        else:
            self.error(["++", "--", "="] + comOp, local_follow)
        return node

    def parse_assVal(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "assVal", "line": line}
        if t_type == "STRLIT":
            self.pos += 1
            node["kind"] = "STRLIT"
            node["value"] = val
        else:
            node["kind"] = "exprDec"
            node["exprDec"] = self.parse_exprDec(local_follow)
        return node
# NO COMOP!!
    def parse_spillOpt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "spillOpt", "args": [], "line": line}
        if t_type == "ID" or t_type == "STRLIT" or val in ["++", "--"] or t_type.startswith("ID"):
            node["args"].append(self.parse_spillOpt1(local_follow | {","}))
            node["args"].extend(self.parse_spillTail(local_follow))
        elif val in local_follow:
            return node
        else:
            self.error(["ID", "STRLIT", "++", "--"] + list(local_follow), local_follow)
        return node

    def parse_spillOpt1(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "spillOpt1", "line": line}
        if t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            # Include "[" in the follow so parse_una1 (inside parse_unaOp)
            # epsilons instead of erroring when a second bracket follows ARR[I].
            node["unaOp"] = self.parse_unaOp({"["} | local_follow)
            # If a second "[" follows, this is a 2D element access: ARR[I][J]
            v, _, _, _ = self.get_token_info()
            if v == "[":
                self.pos += 1
                node["index2"] = self.parse_index({"]"})
                self.match("]")
                # Optional post-increment/decrement after the 2D index
                v2, _, _, _ = self.get_token_info()
                if v2 in {"++", "--"}:
                    node["op"] = v2
                    self.pos += 1
        elif t_type == "STRLIT":
            self.pos += 1
            node["kind"] = "STRLIT"
            node["value"] = val
        elif val in ["++", "--"]:
            node["kind"] = val
            self.pos += 1
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex(local_follow)
        else:
            self.error(["ID", "STRLIT", "++", "--"], local_follow)
        return node

    def parse_spillTail(self, local_follow):
        items = []
        val, t_type, line, col = self.get_token_info()
        if val == ",":
            self.pos += 1
            items.append(self.parse_spillOpt1(local_follow | {","}))
            items.extend(self.parse_spillTail(local_follow))
        elif val in local_follow:
            return items
        else:
            expected = [","] + list(local_follow)
            prev_val, prev_type, _, _ = self.tokens[self.pos - 1] if self.pos > 0 else (None, None, None, None)
            if prev_type == "ID" or (prev_type and prev_type.startswith("ID")):
                if "[" not in expected: expected.append("[")
                if "++" not in expected: expected.append("++")
                if "--" not in expected: expected.append("--")
            self.error(sorted(list(set(expected))), local_follow)
        return items

    def parse_din(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "din", "line": line}
        if t_type in FST["dtype1"]:
            node["kind"] = "decl"
            node["dtype"] = self.parse_dtype1({";"})
            node["name"] = self.match("ID")
            node["dinTail"] = self.parse_dinTail(local_follow)
        elif t_type == "ID" or t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            node["dinTail1"] = self.parse_dinTail1(local_follow)
        elif val == "echo":
            self.pos += 1
            node["kind"] = "echo"
            node["name"] = self.match("ID")
            self.match("(")
            node["echOp"] = self.parse_echOp({")"})
            self.match(")")
            node["exprTail"] = self.parse_expr_or_tail(local_follow)
        elif val in ["++", "--"]:
            node["kind"] = val
            self.pos += 1
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex(local_follow)
            node["exprTail"] = self.parse_expr_or_tail(local_follow)
        else:
            self.error(list(FST["dtype1"]) + ["ID", "echo", "++", "--"], local_follow)
        return node

    def parse_dinTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "dinTail", "line": line}
        if val == "=":
            self.pos += 1
            node["value"] = self.parse_exprDec(local_follow)
        elif val in local_follow:
            return node
        else:
            self.error(["="] + list(local_follow), local_follow)
        return node

    def parse_dinTail1(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "dinTail1", "line": line}
        operators = {"+", "-", "*", "/", "%", "//", "^", "==", "!=", ">", "<", ">=", "<=", "&&", "||"}
        if val == "=":
            self.pos += 1
            node["value"] = self.parse_exprDec(local_follow)
        elif val in local_follow:
            return node
        elif val == "[":
            self.pos += 1
            node["index"] = self.parse_index({"]"})
            self.match("]")
            self.parse_una1({"="} | local_follow)
            node["dinTail"] = self.parse_dinTail(local_follow)
        elif val in {"++", "--"} or val in operators:
            node["una1"] = self.parse_una1(local_follow)
            node["exprTail"] = self.parse_expr_or_tail(local_follow)
        else:
            self.error(["=", "[", "++", "--"] + sorted(list(operators)) + list(local_follow), local_follow)
        return node

    def parse_dup(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "dup", "line": line}
        if t_type == "ID" or t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            node["dupTail"] = self.parse_dupTail(local_follow)
        elif val in ["++", "--"]:
            node["kind"] = val
            self.pos += 1
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex(local_follow)
            node["exprTail"] = self.parse_expr_or_tail(local_follow)
        else:
            self.error(["ID", "++", "--"], local_follow)
        return node

    def parse_dupTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "dupTail", "line": line}
        comOp = ["+=", "-=", "*=", "/=", "%=", "//=", "^="]
        if val in ["++", "--", "["]:
            node["unaOp"] = self.parse_unaOp(local_follow)
            node["exprTail"] = self.parse_expr_or_tail(local_follow)
        elif val in comOp:
            node["op"] = val
            self.pos += 1
            node["exprDec"] = self.parse_exprDec(local_follow)
        elif val in local_follow:
            return node
        else:
            self.error(["++", "--", "["] + comOp, local_follow)
        return node

    def parse_loopStmt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "loopStmt", "stmts": [], "line": line}
        if val == "hope":
            self.pos += 1
            stmt = {"type": "hope", "line": line}
            self.match("(")
            stmt["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match("{")
            stmt["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
            stmt["hopeTailLoop"] = self.parse_hopeTailLoop(local_follow)
            node["stmts"].append(stmt)
            rest = self.parse_loopStmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val == "core":
            self.pos += 1
            stmt = {"type": "core", "line": line}
            self.match("(")
            stmt["condition"] = self.parse_coreCon({")"})
            self.match(")")
            self.match("{")
            stmt["body"] = self.parse_coreLoopBody({"}"})
            self.match("}")
            node["stmts"].append(stmt)
            rest = self.parse_loopStmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val == "down":
            self.pos += 1
            self.match(";")
            node["break"] = "down"
            return node
        elif val == "over":
            self.pos += 1
            self.match(";")
            node["continue"] = "over"
            return node
        elif val == "closure":
            self.pos += 1
            node["return"] = self.parse_closureCon({";"})
            self.match(";")
            return node
        elif t_type in FST["stmtOp"] or val in FST["stmtOp"] or t_type.startswith("ID"):
            node["stmts"].append(self.parse_stmtOp(local_follow))
            rest = self.parse_loopStmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val in local_follow:
            return node
        else:
            expected = ["hope", "core", "down", "over", "closure"] + list(FST["stmtOp"])
            self.error(expected, local_follow)
        return node

    def parse_hopeTailLoop(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "hopeTailLoop", "line": line}
        loop_follow = local_follow | {"hope", "core", "down", "over", "closure"} | set(FST["stmtOp"])
        if val == "despair":
            self.pos += 1
            node["despairOptLoop"] = self.parse_despairOptLoop(local_follow)
        elif val in loop_follow or t_type.startswith("ID"):
            return node
        else:
            self.error(["despair"] + sorted(list(loop_follow)), local_follow)
        return node

    def parse_despairOptLoop(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "despairOptLoop", "line": line}
        if val == "hope":
            self.pos += 1
            self.match("(")
            node["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match("{")
            node["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
            node["hopeTailLoop"] = self.parse_hopeTailLoop(local_follow)
        elif val == "{":
            self.pos += 1
            node["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
        else:
            self.error(["hope", "{"], local_follow)
        return node

    def parse_coreCon(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreCon", "line": line}
        node["coreAdd"] = self.parse_core_add(local_follow)
        return node

    def parse_core_add(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreAdd", "line": line}
        node["left"] = self.parse_core_mul({"+", "-"} | local_follow)
        node["tail"] = self.parse_core_add_tail(local_follow)
        return node

    def parse_core_add_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreAddTail", "op": None, "right": None, "line": line}
        if val in {"+", "-"}:
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_core_mul({"+", "-"} | local_follow)
            node["tail"] = self.parse_core_add_tail(local_follow)
        else:
            return node
        return node

    def parse_core_mul(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreMul", "line": line}
        node["left"] = self.parse_core_exp({"*", "/", "%", "//"} | local_follow)
        node["tail"] = self.parse_core_mul_tail(local_follow)
        return node

    def parse_core_mul_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreMulTail", "op": None, "right": None, "line": line}
        if val in {"*", "/", "%", "//"}:
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_core_exp({"*", "/", "%", "//"} | local_follow)
            node["tail"] = self.parse_core_mul_tail(local_follow)
        else:
            return node
        return node

    def parse_core_exp(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreExp", "line": line}
        node["left"] = self.parse_core_unary({"^"} | local_follow)
        node["tail"] = self.parse_core_exp_tail(local_follow)
        return node

    def parse_core_exp_tail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreExpTail", "op": None, "right": None, "line": line}
        if val == "^":
            node["op"] = val
            self.pos += 1
            node["right"] = self.parse_core_unary({"^"} | local_follow)
            node["tail"] = self.parse_core_exp_tail(local_follow)
        else:
            return node
        return node

    def parse_core_unary(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreUnary", "line": line}
        if val in {"++", "--"}:
            node["kind"] = val
            self.pos += 1
            node["name"] = self.match("ID")
            node["eleIndex"] = self.parse_eleIndex(local_follow)
        else:
            node["kind"] = "primary"
            node["primary"] = self.parse_core_primary(local_follow)
        return node

    def parse_core_primary(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "corePrimary", "line": line}
        if t_type in {"INTLIT", "CHARLIT"}:
            node["kind"] = t_type
            node["value"] = val
            self.pos += 1
        elif val == "echo":
            self.pos += 1
            node["kind"] = "echo"
            node["name"] = self.match("ID")
            self.match("(")
            node["echOp"] = self.parse_echOp({")"})
            self.match(")")
        elif val == "(":
            self.pos += 1
            node["kind"] = "grouped"
            node["inner"] = self.parse_coreCon({")"})
            self.match(")")
        elif t_type == "ID" or t_type.startswith("ID"):
            node["kind"] = "ID"
            node["name"] = val
            self.pos += 1
            node["postfix"] = self.parse_postfix(local_follow)
        else:
            self.error(["INTLIT", "CHARLIT", "ID", "echo", "("], local_follow)
        return node

    def parse_memVal(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        if t_type in FST["memVal"]:
            self.pos += 1
            return val
        else:
            self.error(list(FST["memVal"]), local_follow)

    def parse_coreLoopBody(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreLoopBody", "cases": [], "line": line}
        if val == "memory":
            self.pos += 1
            entry = {"line": line}
            entry["memVal"] = self.parse_memVal({":"})
            self.match(":")
            self.match("{")
            entry["loopStmt"] = self.parse_loopStmt({"}"})
            self.match("}")
            node["cases"].append(entry)
            rest = self.parse_coreLoopBody(local_follow)
            node["cases"].extend(rest["cases"])
        elif val == "default":
            self.pos += 1
            self.match(":")
            self.match("{")
            node["default"] = self.parse_loopStmt({"}"})
            self.match("}")
        elif val in local_follow:
            return node
        else:
            self.error(["memory", "default"] + list(local_follow), local_follow)
        return node

    def parse_closureCon(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "closureCon", "line": line}
        if t_type in FST["assVal"] or val in FST["assVal"] or t_type.startswith("ID"):
            node["value"] = self.parse_assVal(local_follow)
        elif val in local_follow:
            return node
        else:
            self.error(["ID", "INTLIT", "FLOATLIT", "CHARLIT", "STRLIT", "echo", "(", "trust", "betray"] + list(local_follow), local_follow)
        return node

    def parse_hopeTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "hopeTail", "line": line}
        if val == "despair":
            self.pos += 1
            node["despairOpt"] = self.parse_despairOpt(local_follow)
        return node

    def parse_despairOpt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "despairOpt", "line": line}
        if val == "hope":
            self.pos += 1
            self.match("(")
            node["condition"] = self.parse_exprDec({")"})
            self.match(")")
            self.match("{")
            node["stmt"] = self.parse_stmt({"closure", "}"})
            node["stmtOpTail"] = self.parse_stmtOpTail({"closure", "}"})
            self.match("}")
            node["hopeTail"] = self.parse_hopeTail(local_follow)
        elif val == "{":
            self.pos += 1
            node["stmt"] = self.parse_stmt({"closure", "}"})
            node["stmtOpTail"] = self.parse_stmtOpTail({"closure", "}"})
            self.match("}")
        else:
            self.error(["hope", "{"] + list(local_follow), local_follow)
        return node

    def parse_stmtOpTail(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "stmtOpTail", "line": line}
        if val == "closure":
            self.pos += 1
            node["return"] = self.parse_closureCon({";"})
            self.match(";")
            return node
        return node

    def parse_coreBody(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreBody", "cases": [], "line": line}
        if val == "memory":
            self.pos += 1
            entry = {"line": line}
            entry["memVal"] = self.parse_memVal({":"})
            self.match(":")
            self.match("{")
            entry["coreStmt"] = self.parse_coreStmt({"}"} | local_follow)
            self.match("}")
            node["cases"].append(entry)
            rest = self.parse_coreLoopBody(local_follow)
            node["cases"].extend(rest["cases"])
        elif val == "default":
            self.pos += 1
            self.match(":")
            self.match("{")
            node["default"] = self.parse_coreStmt({"}"})
            self.match("}")
        elif val in local_follow:
            return node
        else:
            self.error(["memory", "default"] + list(local_follow), local_follow)
        return node

    def parse_coreStmt(self, local_follow):
        val, t_type, line, col = self.get_token_info()
        node = {"type": "coreStmt", "stmts": [], "line": line}
        if val == "over" or t_type == "over":
            self.pos += 1
            self.match(";")
            node["continue"] = "over"
            return node
        elif val == "closure":
            self.pos += 1
            node["return"] = self.parse_closureCon({";"})
            self.match(";")
            return node
        elif t_type in FST["stmt"] or val in FST["stmt"] or t_type.startswith("ID") or val == "over":
            node["stmts"].append(self.parse_stmt({"over", "closure", "}"} | local_follow))
            rest = self.parse_coreStmt(local_follow)
            node["stmts"].extend(rest["stmts"])
        elif val in local_follow:
            return node
        else:
            self.error(["over", "closure"] + list(FST["stmt"]), local_follow)
        return node

# okay dito natin cont. ang mga explanation :) 
def perform_syntax_analysis(tokens, terminal):
    parser = SyntaxAnalyzer(tokens, terminal)
    try:
        if not tokens:
            return (False, "Syntax Error: No code provided.", None)

        parse_tree = parser.parse_program()
        val, t_type, line, col = parser.get_token_info()
        if t_type != "$":
            parser.error(["$"], [])

        return (True, "SYNTAX ANALYSIS: SUCCESS!", parse_tree)

    except Exception as e:
        error_message = str(e)
        return (False, error_message, None)